# Generated by Django 3.2.5 on 2021-07-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_post',
            field=models.TextField(max_length=600),
        ),
    ]
